### PR TITLE
feat: upgrade to PostCSS 8

### PR DESCRIPTION
**Pull request by armano2**
This PR upgrades the module to PostCSS 8 along with a few other changes:

- Upgraded ESLint to V7
- Upgraded postcss-tape to V6
- Changed the engines since PostCSS supports only Node.js 10 and up
- Travis tests run on Node.js 10 and 12
- Removed babel / rollup since all features used are now available in Node.js

see csstools/postcss-preset-env#191

### CODE REVIEW

**Comment by armano2** [comment]
@jonathantneal i rebased it against master

**Comment by await-ovo** [comment]
@jonathantneal please take the time to review ~

**Comment by AlejandroAkbal** [comment]
I would appreciate if this PR could be merged, I need to use it on a PostCSS 8 project.

**Comment by megawebmaster** [comment]
Is there any chance this PR will be merged?

**Pull request merged**
